# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='example@email.com', max_length=128)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('fee', models.FloatField(default=0)),
                ('performance', models.IntegerField(default=50)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('trusted_by', models.IntegerField(default=0)),
                ('blocked_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='NOTHINGS HAPPENED', max_length=50)),
                ('article', models.CharField(default='STILL NOTHING', max_length=300)),
                ('url', models.CharField(default='/', max_length=300)),
                ('image', models.CharField(default='NONE', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='X', max_length=8)),
                ('name', models.CharField(default='STOCK', max_length=32)),
                ('price', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=512)),
                ('salt', models.BigIntegerField(null=True)),
                ('email', models.CharField(default='example@email.com', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('watching', models.BooleanField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graaftrade.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graaftrade.User')),
            ],
        ),
    ]
