# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='website',
            field=models.CharField(default='website.com', max_length=128),
        ),
    ]
