# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='X', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('newprice', models.FloatField(default=0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graaftrade.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='User_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graaftrade.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@email.com', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='user_stock',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graaftrade.User'),
        ),
    ]
