# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0002_broker_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='website',
        ),
    ]
