# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0005_chat_chat_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_content',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
