# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0007_auto_20160609_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='timestamp',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='article',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='heading',
            new_name='title',
        ),
    ]
