# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0008_auto_20160609_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NEWS JUST IN CYRUS IS A STONER', max_length=50)),
                ('link', models.CharField(default='/', max_length=300)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graaftrade.Stock')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(default='http://www.eonline.com/eol_images/Entire_Site/2013317/rs_560x415-130417122053-1024.DazedConfused.mh.041713.jpg', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(default='HE LIKES SMOKING BARE KUSH', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='NEWS JUST IN CYRUS IS A STONER', max_length=50),
        ),
    ]
