# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0010_stock_news_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_news',
            name='title',
            field=models.CharField(default='NEWS JUST IN CYRUS IS A STONER', max_length=300),
        ),
    ]
