# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graaftrade', '0011_auto_20160609_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='email',
        ),
        migrations.AddField(
            model_name='broker',
            name='faqs',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='broker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graaftrade.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='isBroker',
            field=models.BooleanField(default=0),
        ),
    ]
